name: Reusable Workflow

on:
  workflow_call:
    inputs:
      pr_id:
        required: true
        type: string

jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - name: Echo PR ID
        run: echo "PR ID is ${{ inputs.pr_id }}"
